---
title: "Products"
author: "Ritu"
date: "Jan 29, 2019"
output: github_document
---

```{r}
rm(list = ls()) ; gc()
```


```{r}
# Import libraries
library(ggplot2)
library(readr)
library(dplyr)
library(igraph)
library(ggraph)
library(tidytext)
library(stringr)
library(tidyr)
library(ggthemes)
library(RColorBrewer)

```


```{r}
# Read data
#setwd("C:\\Users\\Ritu\\Documents\\Learning\\Self\\CS\\code\\Selenium")
data <- read_csv("products.csv")

```


```{r}
# View data
dim(data)
names(data)
View(data)
```


```{r}
# converting to tidy text
tidy_new <- data %>% unnest_tokens(word_new, Products) %>% filter(!word_new %in% stop_words$word,
         str_detect(word_new, "[a-z]"))


```



```{r}
# Top words
c <- tidy_new %>% count(word_new, sort=TRUE) %>% filter(n > 30) %>% mutate(word = reorder(word_new, n))

c

colourCount = nrow(c)
getPalette = colorRampPalette(brewer.pal(3, "PuBu"))

tidy_new %>%
  count(word_new, sort = TRUE) %>%
  filter(n > 30) %>%
  mutate(word = reorder(word_new, n)) %>%
  ggplot(aes(word, n, fill=getPalette(colourCount))) +
  geom_col() +
  xlab(NULL) +
  ylab(NULL) +
  theme_bw(base_size = 18)  +
  scale_fill_manual(values=getPalette(colourCount)) +
  theme(axis.ticks = element_blank()) + 
  theme(legend.position="none") + 
  coord_flip()
```


```{r}
# N-grams Analysis
bigrams_new <- data %>% unnest_tokens(bigram, Products, token = "ngrams", n = 2) 

bigrams_new %>% 
  count(bigram, sort = TRUE)

```

```{r}
# Filter stopwords
bigrams_separated <- bigrams_new %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_counts

```


```{r}
set.seed(1234)

bigram_counts %>%
  filter(n > 10) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n), edge_colour = "cyan4") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE, 
                 point.padding = unit(0.2, "lines")) +
  theme_void()
```

